"""add quantity fields to events

Revision ID: 20374a9f1d07
Revises: d78bfddaf1c1
Create Date: 2026-05-14 18:43:10.509105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20374a9f1d07'
down_revision: Union[str, None] = 'd78bfddaf1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('available_quantities', sa.String(), nullable=True))
    op.drop_column('events', 'valid_quantities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('valid_quantities', sa.VARCHAR(), nullable=True))
    op.drop_column('events', 'available_quantities')
    # ### end Alembic commands ###
