"""add_indexes

Revision ID: 3286c160d642
Revises: c5fe4092d1d1
Create Date: 2026-05-23 09:46:09.891396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3286c160d642'
down_revision: Union[str, None] = 'c5fe4092d1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing_availability')
    op.create_index('ix_alert_log_listing_alerted', 'alert_log', ['listing_id', 'alerted_at'], unique=False)
    op.create_index('ix_listings_event_id', 'listings', ['event_id'], unique=False)
    op.create_index('ix_price_snapshots_listing_id', 'price_snapshots', ['listing_id'], unique=False)
    op.create_index('ix_user_watches_listing_id', 'user_watches', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_watches_listing_id', table_name='user_watches')
    op.drop_index('ix_price_snapshots_listing_id', table_name='price_snapshots')
    op.drop_index('ix_listings_event_id', table_name='listings')
    op.drop_index('ix_alert_log_listing_alerted', table_name='alert_log')
    op.create_table('listing_availability',
    sa.Column('listing_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), nullable=False),
    sa.Column('last_seen_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('listing_id', 'quantity')
    )
    # ### end Alembic commands ###
