"""add quantity to events

Revision ID: 4f9a34d2952a
Revises: 9e74294e66f9
Create Date: 2026-05-14 18:00:29.975151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9a34d2952a'
down_revision: Union[str, None] = '9e74294e66f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('quantity', sa.Integer(), nullable=True))
    op.drop_column('user_watches', 'min_drop_pct')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_watches', sa.Column('min_drop_pct', sa.FLOAT(), nullable=True))
    op.drop_column('events', 'quantity')
    # ### end Alembic commands ###
