"""add min_drop_pct to user_watches

Revision ID: 9e74294e66f9
Revises: 6452389a40ed
Create Date: 2026-05-14 09:31:36.672338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e74294e66f9'
down_revision: Union[str, None] = '6452389a40ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_watches', sa.Column('min_drop_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_watches', 'min_drop_pct')
    # ### end Alembic commands ###
