"""add raw_offers and status to events

Revision ID: a642082085a9
Revises: 20374a9f1d07
Create Date: 2026-05-14 20:54:37.308749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a642082085a9'
down_revision: Union[str, None] = '20374a9f1d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('raw_offers', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('status', sa.String(), server_default='ready', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'status')
    op.drop_column('events', 'raw_offers')
    # ### end Alembic commands ###
