"""add raw_offers table

Revision ID: a832bb0b5e20
Revises: a642082085a9
Create Date: 2026-05-14 21:51:58.551692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a832bb0b5e20'
down_revision: Union[str, None] = 'a642082085a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('list_price', sa.Float(), nullable=False),
    sa.Column('sellable_quantities', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('inventory_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('events', 'raw_offers')
    op.drop_column('events', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'ready'"), nullable=False))
    op.add_column('events', sa.Column('raw_offers', sa.TEXT(), nullable=True))
    op.drop_table('raw_offers')
    # ### end Alembic commands ###
