"""add_quantity_to_listings_and_watches

Revision ID: ac62824ab045
Revises: 3286c160d642
Create Date: 2026-05-23 13:32:27.454005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac62824ab045'
down_revision: Union[str, None] = '3286c160d642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('user_watches', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_watches', 'quantity')
    op.drop_column('listings', 'quantity')
    # ### end Alembic commands ###
