"""add valid quantities to events

Revision ID: d78bfddaf1c1
Revises: 4f9a34d2952a
Create Date: 2026-05-14 18:26:29.544595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78bfddaf1c1'
down_revision: Union[str, None] = '4f9a34d2952a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('valid_quantities', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'valid_quantities')
    # ### end Alembic commands ###
