"""add_availability_watches

Revision ID: e7b8d587ff4c
Revises: ac62824ab045
Create Date: 2026-05-23 17:30:02.687814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b8d587ff4c'
down_revision: Union[str, None] = 'ac62824ab045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('alert_cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_alerted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'section_name', 'quantity', name='uq_availability_watch_event_section_qty')
    )
    op.create_index('ix_availability_watches_event_id', 'availability_watches', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_availability_watches_event_id', table_name='availability_watches')
    op.drop_table('availability_watches')
    # ### end Alembic commands ###
