"""add restock fields

Revision ID: e7cc3027e9bc
Revises: 76ca67e4a769
Create Date: 2026-05-15 10:02:16.747257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7cc3027e9bc'
down_revision: Union[str, None] = '76ca67e4a769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_offers')
    op.add_column('listings', sa.Column('previously_available', sa.Boolean(), nullable=True))
    op.add_column('user_watches', sa.Column('notify_on_restock', sa.Boolean(), nullable=False))
    op.alter_column('user_watches', 'target_price',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_watches', 'target_price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.drop_column('user_watches', 'notify_on_restock')
    op.drop_column('listings', 'previously_available')
    op.create_table('raw_offers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('section', sa.VARCHAR(), nullable=False),
    sa.Column('list_price', sa.FLOAT(), nullable=False),
    sa.Column('sellable_quantities', sa.VARCHAR(), nullable=False),
    sa.Column('scraped_at', sa.DATETIME(), nullable=False),
    sa.Column('inventory_type', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
